apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-apps
spec:
  interval: 10m
  ref:
    branch: ${GIT_BRANCH}
  # secretRef:
  #   name: flux-apps
  url: https://github.com/sestegra/d1-apps.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps
spec:
  serviceAccountName: flux-apps
  interval: 12h
  retryInterval: 3m
  path: ./update
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-apps
